version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Generate Makefile
          command: ruby ext/arraybuffer/extconf.rb
      - run:
          name: Compile gem
          command: make
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run rspec
          command: bundle exec rspec -I.
